Shawn June

# Lab Assignment 2: How to Load CSV, ASCII, and other data into Python
## DS 6001

100 points

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

## Problem 1

There are several data files attached to this lab assignment, with different extensions. First, download all of these data files, and save them in the same folder on your local machine. Your task in the following questions is to load each file into Python correctly, so that you can begin the process of data cleaning. If the variable names are included in the file, use those names to name the columns. If the variable names are not included, use these names in order:

In [130]:
import pandas as pd
import numpy as np
import os

In [164]:
os.chdir(
    "/Users/shawnjune/Desktop/University of Virginia (UVA)/"
    "School of Data Science/Courses/Fall 2026/5 Understanding Uncertainty/"
    "UU_F26_templates/Data_Engineering_I_DS6001/lab data"
)

os.getcwd()

'/Users/shawnjune/Desktop/University of Virginia (UVA)/School of Data Science/Courses/Fall 2026/5 Understanding Uncertainty/UU_F26_templates/Data_Engineering_I_DS6001/lab data'

In [132]:
os.chdir("/Users/shawnjune/Desktop/University of Virginia (UVA)/School of Data Science/Courses/Fall 2026/5 Understanding Uncertainty/UU_F26_templates/Data_Engineering_I_DS6001/lab data")

In [133]:
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]

### Part a
Import the packages you will need. Then write code to change the working directory to the folder in which you saved the data files, run the code displayed above to create the `column_names` list, load `data_clean.csv`, and display the output of the `.info()` method of `data_clean`. [4 points]

In [134]:
data_clean = pd.read_csv("data_clean.csv")

data_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    str
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), str(1)
memory usage: 13.5 KB

### Part b
Load `data1.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [ ]:
data1 = pd.read_csv("data1.csv", skiprows=2)

data1.head()
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    str
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), str(1)
memory usage: 13.5 KB

Answer: I first loaded the file and inspected it with head() and info(). The first two rows contained source information rather than data, so I used skiprows=2 to make the actual variable names the header.

### Part c
Load `data2.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [6 points]

In [136]:
data2 = pd.read_csv("data2.txt")

data2.head()

,"Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,URL: http://worldhappiness.report/ed/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
2,"/The following countries comprise the ""very ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
4,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340

In [137]:
data2 = pd.read_csv(
    "data2.txt",
    skiprows=2,
    comment="/"
)

data2.head()
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    str
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), str(1)
memory usage: 13.5 KB

Answer: I first loaded the file and inspected it with head() and info(). The first two rows contained source information, and additional lines beginning with / were comments, so I used skiprows=2 and comment="/" to load only the actual data.

### Part d
Load `data3.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [138]:
data3 = pd.read_csv("data3.txt")

data3.head()

  Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)\t\t\t\t\t\t\t\t\t\t
0  URL: http://worldhappiness.report/ed/2018\t\t\...
1  Country\tHappiness score\tWhisker-high\tWhiske...
2  Finland\t7.632\t7.695\t7.569\t2.595\t1.305\t1....
3  Norway\t7.594\t7.657\t7.53\t2.383\t1.456\t1.58...
4  Denmark\t7.555\t7.623\t7.487\t2.37\t1.351\t1.5...

In [139]:
data3 = pd.read_csv(
    "data3.txt",
    sep="\t",
    skiprows=2
)

data3.head()
data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    str
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), str(1)
memory usage: 13.5 KB

Answer: I first loaded the file and inspected it with head() and info(). The file used tabs instead of commas and had two source lines before the header, so I used sep="\t" and skiprows=2.

### Part e
Load `data4.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [140]:
data4 = pd.read_csv("data4.txt")

data4.head()

  Finland$7.632$7.695$7.569$2.595$1.305$1.592$0.874$0.681$0.192$0.393
0  Norway$7.594$7.657$7.530$2.383$1.456$1.582$0.8...
1  Denmark$7.555$7.623$7.487$2.370$1.351$1.590$0....
2  Iceland$7.495$7.593$7.398$2.426$1.343$1.644$0....
3  Switzerland$7.487$7.570$7.405$2.320$1.420$1.54...
4  Netherlands$7.441$7.498$7.384$2.448$1.361$1.48...

In [141]:
data4 = pd.read_csv(
    "data4.txt",
    sep="$",
    header=None,
    names=column_names
)

data4.head()
data4.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    str
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), str(1)
memory usage: 13.5 KB

Answer: I first loaded the file and inspected it with head() and info(). The values were separated by $ signs and the file did not include variable names, so I used sep="$", header=None, and the provided column_names list.

### Part f
Load `data5.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [142]:
import numpy as np
import pandas as pd

In [143]:
data5 = pd.read_csv("data5.csv")

data5.tail()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076
156,"Source: The World Happiness Report (2018), The...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,URL: http://worldhappiness.report/ed/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [144]:
data5 = pd.read_csv(
    "data5.csv",
    skipfooter=2,
    engine="python"
)

data5.tail()
data5.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    str
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), str(1)
memory usage: 13.5 KB

Answer: I first loaded the file and inspected the end of the dataframe with tail(). The last two rows contained source information rather than country data, so I used skipfooter=2 to remove them.

### Part g
Load `data6.dat`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (Note: for this question, your result won't look *exactly* like data_clean.csv, and that is OK.) [6 points]

In [167]:
import numpy as np
data6 = pd.read_csv('data6.dat')
data6.replace(999.000, np.nan)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,NaN,NaN,NaN,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,NaN,NaN,1.582,NaN,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,NaN,0.683,0.284,0.408
3,Iceland,7.495,7.593,NaN,2.426,1.343,1.644,0.914,0.677,0.353,NaN
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,999,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,NaN,0.064
152,Tanzania,NaN,NaN,3.193,0.628,NaN,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,NaN,3.123,1.691,0.337,NaN,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,NaN,0.038
155,Burundi,2.905,3.074,NaN,1.752,0.091,NaN,0.145,0.065,0.149,0.076

Answer: Had to change several numbers to not a Number (NaN) using .replace() method

### Part h
Load `data7.xlsx`, which is an Excel file. Keep only the sheet named “Data”. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [146]:
data7=pd.read_excel('data7.xlsx')
data7

  Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)
0          URL: http://worldhappiness.report/ed/2018

In [147]:
df = pd.read_excel('data7.xlsx', sheet_name='Data')
df

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

Answer: It was an excel file so then we knew to read excel. Upon review document we
realized the required data was under a different tab "name." Further research concluded that
we needed to use the df = pd function sheet name "argument" from what we had used
earlier in the week from our live coding. Once we implemented the code it corrected the
action and worked.

### Part i
Load `data8.dta`, which is a Stata 13 file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [148]:
help(pd.read_stata)

Help on function read_stata in module pandas:

read_stata(
    filepath_or_buffer: FilePath | ReadBuffer[bytes],
    *,
    convert_dates: bool = True,
    convert_categoricals: bool = True,
    index_col: str | None = None,
    convert_missing: bool = False,
    preserve_dtypes: bool = True,
    columns: Sequence[str] | None = None,
    order_categoricals: bool = True,
    chunksize: int | None = None,
    iterator: bool = False,
    compression: CompressionOptions = 'infer',
    storage_options: StorageOptions | None = None
) -> DataFrame | StataReader
    Read Stata file into DataFrame.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be: ``file://localhost/path/to/table.dta``.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method,
        such as a file handle (e.g. via builtin ``open`` function)
        or ``StringIO``.
    convert_dates : bool, default True
        Convert date variables to DataFrame time values.
    convert_categoricals : bool, default True
        Read value labels and convert columns to Categorical/Factor variables.
    index_col : str, optional
        Column to set as index.
    convert_missing : bool, default False
        Flag indicating whether to convert missing values to their Stata
        representations.  If False, missing values are replaced with nan.
        If True, columns containing missing values are returned with
        object data types and missing values are represented by
        StataMissingValue objects.
    preserve_dtypes : bool, default True
        Preserve Stata datatypes. If False, numeric data are upcast to pandas
        default types for foreign data (float64 or int64).
    columns : list or None
        Columns to retain.  Columns will be returned in the given order.  None
        returns all columns.
    order_categoricals : bool, default True
        Flag indicating whether converted categorical data are ordered.
    chunksize : int, default None
        Return StataReader object for iterations, returns chunks with
        given number of lines.
    iterator : bool, default False
        Return StataReader object.
    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and
        'filepath_or_buffer' is path-like, then detect compression from the
        following extensions: '.gz', '.bz2', '.zip', '.xz', '.zst', '.tar',
        '.tar.gz', '.tar.xz' or '.tar.bz2' (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one
        data file to be read in. Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set to one of
        {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.
    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    Returns
    -------
    DataFrame, pandas.api.typing.StataReader
        If iterator or chunksize, returns StataReader, else DataFrame.

    See Also
    --------
    io.stata.StataReader : Low-level reader for Stata data files.
    DataFrame.to_stata: Export Stata data files.

    Notes
    -----
    Categorical variables read through an iterator may not have the same
    categories and dtype. This occurs when  a variable stored in a DTA
    file is associated to an incomplete set of value labels that only
    label a strict subset of the values.

    Examples
    --------

    Creating a dummy stata for this example

    >>> df = pd.DataFrame(
    ...     {
    ...         "animal": ["falcon", "parrot", "falcon", "parrot"],
    ...         "speed": [350, 18, 361, 15],
    ...     }
    ... )  # doctest: +SKIP
    >>> df.to_stata("animals.dta")  # doctest: +SKIP

    Read a Stata dta file:

    >>> df = pd.read_stata("animals.dta")  # doctest: +SKIP

    Read a Stata dta file in 10,000 line chunks:

    >>> values = np.random.randint(
    ...     0, 10, size=(20_000, 1), dtype="uint8"
    ... )  # doctest: +SKIP
    >>> df = pd.DataFrame(values, columns=["i"])  # doctest: +SKIP
    >>> df.to_stata("filename.dta")  # doctest: +SKIP

    >>> with pd.read_stata('filename.dta', chunksize=10000) as itr:  # doctest: +SKIP
    >>>     for chunk in itr:
    ...         # Operate on a single chunk, e.g., chunk.mean()
    ...         pass  # doctest: +SKIP

In [149]:
data8=pd.read_stata('data8.dta')
data8.columns=column_names
data8

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

Answer: We saw there was a pandas funciton read stata which matched our stata function.
We didn't see any issue; however, upon further inspection we saw that the column heads
were not matching up in capitalization, punctuation, spacing, etc. Instead of trying to fix
them we replaced them with the .columns method.

### Part j
Load `data9.sav`, which is an SPSS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [150]:
data9=pd.read_spss('data9.sav')
data9.columns=column_names
data9

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

Answer: We saw this file was an SPSS file, so we used pd.read_spss() to load in the data.
Again, the columns didn't load in correctly, so we replaced them with the .columns method.

### Part k
Load `data10.xpt`, which is a SAS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. 

(If some of the country names display as `b'Finland'`, don't worry about that.)

(But if you are still worrying about it ... issues like `b'Finland'` indicate a [character encoding](https://en.wikipedia.org/wiki/Character_encoding) issue, in which SAS uses a different encoding method than Python. In this case Python uses a default encoding called [UTF-8](https://en.wikipedia.org/wiki/UTF-8) and this SAS file has encoded characters using [Latin-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1). To get around this issue, add the `encoding='latin-1'` argument to your read method.) 

[4 points]

In [151]:
data10=pd.read_sas('data10.xpt', encoding='latin-1')
data10

,COUNTRY,HAPPINES,WHISKERH,WHISKERL,DYSTOPIA,EXPLAINE,EXPLAIN2,EXPLAIN3,EXPLAIN4,EXPLAIN5,EXPLAIN6
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592000e+00,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582000e+00,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590000e+00,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644000e+00,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549000e+00,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073000e+00,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,9.910000e-01,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,6.080000e-01,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,5.397605e-79,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,6.270000e-01,0.145,0.065,0.149,0.076

In [152]:
data10 = pd.read_sas('data10.xpt', encoding='latin-1')
data10.columns = column_names
data10

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592000e+00,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582000e+00,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590000e+00,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644000e+00,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549000e+00,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073000e+00,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,9.910000e-01,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,6.080000e-01,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,5.397605e-79,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,6.270000e-01,0.145,0.065,0.149,0.076

Answer: First we loaded the data with pd.read_sas(). We saw one of the columns was not
displaying correctly. It was in scientific notation, so we rounded the variable to the 3rd
decimal place. Lastly, we correctly the column names Then, we rounded one of the columns.

### Part l
Please load the `data11.txt` file, which is a fixed width file. The columns are defined as follows:

| Variable                                   | Width | Start | End |
|--------------------------------------------|-------|-------|-----|
| Country                                    | 24    | 1     | 24  |
| Happiness score                            | 5     | 25    | 29  |
| Whisker-high                               | 5     | 30    | 34  |
| Whisker-low                                | 5     | 35    | 39  |
| Dystopia (1.92) + residual                 | 5     | 40    | 44  |
| Explained by: GDP per capita               | 5     | 45    | 49  |
| Explained by: Social support               | 5     | 50    | 54  |
| Explained by: Healthy life expectancy      | 5     | 55    | 59  |
| Explained by: Freedom to make life choices | 5     | 60    | 64  |
| Explained by: Generosity                   | 5     | 65    | 69  |
| Explained by: Perceptions of corruption    | 5     | 70    | 74  |

Then save the this loaded data frame as a CSV file on your local machine. Be sure to use a unique filename so as not to overwrite any existing files. [10 points]

In [153]:
widths = [24, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

data11 = pd.read_fwf(
    'data11.txt',
    widths=widths,
    header=None,
    names=column_names
)

data11

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

Answer: We realized that we needed to create an Excel Spreadsheet from the original data
set so we did that. From there we saved the new file called "widths.csv" which contained the
description file for splitting the fixed width file appropriately. The loaded the data with
pd.read_fwf(). Then we saw the header was reading the first row as the header. So we set the
header parameter to none which aligned the header and the values correctly. Lastly, we
correctly the column names from the data11 file

## Problem 2
This problem walks through how to wrangle some difficult real-world Excel data into Python. This problem is guided, but later in the semester you'll be asked more often to do work with less guidance. 

The file named "epa_data.xlsx" contains data on the reproduction and growth of nine different plant species, measured once in 2010 and once in 2011. The data were compiled from the [EPA's repository](https://catalog.data.gov/dataset/18-excel-spreadsheets-by-species-and-year-giving-reproduction-and-growth-data-one-excel-sp) on data.gov. I placed all of the data into a single file, where the different species/year combinations are placed in different sheets. The file also includes a sheet for herbicide treatment chemistry data, and one sheet for a ReadMe describing some of the columns in the growth data.

### Part a
If you load an Excel file with multiple sheets into Python using the `sheet_name=None` argument, then every sheet's data will be stored in one big Python dictionary. 

We will discuss dictionaries (and JSON formatted data) in depth in module 3. However, for this problem, there a few points to know about dictionaries:

* Dictionaries are similar to lists, except that they are denoted with curly braces {} instead of square braces [], and that entries in the dictionary are indexed by names instead of numeric positions.

* Entries in a dictionary are called values, and the names attached to the entries are called keys. Your output will set the former sheet names as the keys for each data table.

* To display one of the values, call the Python variable that contains the dictionary, and index it by the value's key. For example, if you save the data as `epadata`, then you can see the 2010 data for species CALE by typing `epadata['CALE 2010']`. 

Load all of the data, across all of the sheets, from this Excel file into Python. Then index to one of the values in the resulting dictionary to display one of the former sheets as a pandas dataframe. [8 points]

In [154]:
epadata = pd.read_excel("epa_data.xlsx", sheet_name=None)

epadata["CALE 2010"]

,Year,Species,site,Plot,Trt,Treatment,pods,sqrtpods,cover0,arsincover0,...,arsincover3,matureseeds,logmatureseeddw,immatureseeddw,logimmatureseeddw,totalseeddw,logtotalseeddw,percentimmatureseed,arsinpercentimmatureseed,Final Comments
0,2010,CALE,Hyslop,4,6,Roundup 0.1,1.0,1.000000,1,0.100167,...,0.141897,0.0957,-1.019043,0.0000,-5.000000,0.0957,-1.019043,0.000000,0.000000,NaN
1,2010,CALE,Hyslop,12,7,Rdup/Bnvl 0.01,6.0,2.449490,2,0.141897,...,0.100167,0.3863,-0.413064,0.0041,-2.386158,0.3904,-0.408479,1.050205,0.102660,NaN
2,2010,CALE,Hyslop,13,5,Roundup 0.01,8.0,2.828427,2,0.141897,...,0.141897,0.2806,-0.551897,0.0031,-2.507240,0.2837,-0.547125,1.092704,0.104724,NaN
3,2010,CALE,Hyslop,15,1,Carrier Control,3.0,1.732051,1,0.100167,...,0.100167,0.0662,-1.179076,0.0001,-3.958607,0.0663,-1.178421,0.150830,0.038847,NaN
4,2010,CALE,Hyslop,17,3,Banvel 0.01,0.0,0.000000,1,0.100167,...,0.141897,0.0000,-5.000000,0.0000,-5.000000,0.0000,-5.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2010,CALE,Botany,382,8,Rdup/Bnvl 0.1,6.0,2.449490,1,0.100167,...,0.000000,0.0116,-1.935168,0.0020,-2.696804,0.0136,-1.866142,14.705882,0.393564,Died after harvest
124,2010,CALE,Botany,384,1,Carrier Control,NaN,NaN,1,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Cover 3 missing, missing at seed collection an..."
125,2010,CALE,Botany,388,3,Banvel 0.01,8.0,2.828427,2,0.141897,...,0.141897,0.4597,-0.337516,0.0004,-3.387216,0.4601,-0.337138,0.086938,0.029489,NaN
126,2010,CALE,Botany,399,8,Rdup/Bnvl 0.1,12.0,3.464102,1,0.100167,...,0.100167,0.2130,-0.671600,0.0068,-2.166853,0.2198,-0.657953,3.093722,0.176810,NaN
127,2010,CALE,Botany,400,2,No Spray,0.0,0.000000,1,0.100167,...,0.141897,0.0000,-5.000000,0.0000,-5.000000,0.0000,-5.000000,NaN,NaN,NaN

### Part b
To see all of the keys in the dictionary, use the `.keys()` method on the data dictionary you created in part a. If you do, you will notice that two keys are not like the others:

* `Solution Chemistry` contains different data: information about common pesticides instead of the growth and reproduction of a particular species of plant.

* `ReadMe` contains descriptions of some columns in the species-level data.

To delete a key and value from a dictionary, use the following syntax `del d[key]`, where `d` is the Python variable that contains the dictionary, and `key` is the name (quotes included) of the key attached to the value you want to remove from the dictionary. If you use this command, the dictionary is altered *in place*, meaning that there is no need to write `d=` before this command in order to make these edits to the dictionary permanent.

Delete the `Solution Chemistry` and `ReadMe` data from the dictionary. [8 points]

In [155]:
epadata.keys()

dict_keys(['CALE 2010', 'CALE 2011', 'ELGL 2010', 'ELGL 2011', 'ERLA 2010', 'ERLA 2011', 'FEID 2010', 'FEID 2011', 'FRVI 2010', 'FRVI 2011', 'IRTE 2010', 'IRTE 2011', 'POGR 2010', 'POGR 2011', 'PRVU 2010', 'PRVU 2011', 'RAOC 2010', 'RAOC 2011', 'Solution Chemistry', 'ReadMe'])

In [156]:
del epadata["Solution Chemistry"]
del epadata["ReadMe"]

In [157]:
epadata.keys()

dict_keys(['CALE 2010', 'CALE 2011', 'ELGL 2010', 'ELGL 2011', 'ERLA 2010', 'ERLA 2011', 'FEID 2010', 'FEID 2011', 'FRVI 2010', 'FRVI 2011', 'IRTE 2010', 'IRTE 2011', 'POGR 2010', 'POGR 2011', 'PRVU 2010', 'PRVU 2011', 'RAOC 2010', 'RAOC 2011'])

### Part c
Combining two data tables with the same columns but entirely different rows is called **appending** data. Our goal is to append all of the remaining data tables together, to create one large dataframe containing all plant species and both 2010 and 2011 data. 

It is only possible, however, to append data if both data tables have exactly the same column names. If a column in one table is not matched in the other table, the column will be populated with missing values for the rows that come from the second table. There are two reasons why columns might not match: the two tables might not contain the same features, or the two tables contain the same feature but named differently in each table. 

For example, in this case, some of the sheets have columns that others do not, such as biomass. Other features are present in every sheet, but with different names: year is sometimes spelled with a capital Y.

To deal with these issues, we will use a loop over the keys in the dictionary you edited in part b. Begin the loop by typing 
```
for df in d.keys():
```
where `d` is the name of your dictionary.

On the next line, indent (which indicates this line should be run within the loop). Then write
```
d[df].columns = d[df].columns.str.lower()
```
which will alter all column names across all of the dataframes to be lower-case.

In addition, some of the column names have extra spaces at the end, and that will make columns fail to match as well. To remove these spaces, add the following line to the loop:

```
d[df].columns = d[df].columns.str.strip()
```
which removes leading and trailing spaces from each column name. [10 points]

In [158]:
for df in epadata.keys():
    epadata[df].columns = epadata[df].columns.str.lower()
    epadata[df].columns = epadata[df].columns.str.strip()

In [159]:
epadata["CALE 2010"].columns

Index(['year', 'species', 'site', 'plot', 'trt', 'treatment', 'pods',
       'sqrtpods', 'cover0', 'arsincover0', 'cover3', 'arsincover3',
       'matureseeds', 'logmatureseeddw', 'immatureseeddw', 'logimmatureseeddw',
       'totalseeddw', 'logtotalseeddw', 'percentimmatureseed',
       'arsinpercentimmatureseed', 'final comments'],
      dtype='str')

### Part d
Use the `pd.concat()` method to append all of the dataframes in your dictionary together. You can pass the entire dictionary to the first argument of `pd.concat()`. Specify `ignore_index=True`, which resets the row numbering instead of bringing in the old row numbers from the individual dataframes. [8 points]

In [160]:
epadf = pd.concat(epadata, ignore_index=True)

epadf

,year,species,site,plot,trt,treatment,pods,sqrtpods,cover0,arsincover0,...,totseeddw,infloroescences,sqrtinfluorescences,atypicalinfluorescences,sqrtatypicalinfluorescences,totalinflorescence,sqrttotalinfluorescences,percentatypical,arsinpercentatypical,treatment #
0,2010,CALE,Hyslop,4,6,Roundup 0.1,1.0,1.000000,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,CALE,Hyslop,12,7,Rdup/Bnvl 0.01,6.0,2.449490,2.0,0.141897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,CALE,Hyslop,13,5,Roundup 0.01,8.0,2.828427,2.0,0.141897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,CALE,Hyslop,15,1,Carrier Control,3.0,1.732051,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,CALE,Hyslop,17,3,Banvel 0.01,0.0,0.000000,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2299,2011,RAOC,Botany,370,8,Rdup+Bnvl 0.2,NaN,NaN,0.2,0.044736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2300,2011,RAOC,Botany,377,3,Banvel 0.1,NaN,NaN,0.5,0.070770,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
2301,2011,RAOC,Botany,379,4,Banvel 0.2,NaN,NaN,0.3,0.054800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
2302,2011,RAOC,Botany,380,2,No Spray,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2303,2011,RAOC,Botany,382,4,Banvel 0.2,NaN,NaN,0.2,0.044736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0

### Part e
Many of the features that were brought into the appended dataframe were only present for one or a small number of the dataframes. Keep only the following features, which are present for most of the species:

In [161]:
cols_to_keep = ['year', 'species', 'site', 'plot', 'trt', 'treatment', 
                'pods', 'cover0', 'arsincover0', 'cover3', 'arsincover3', 
                'cover5', 'arsincover5']

In [162]:
final_data = epadf[cols_to_keep]

final_data

,year,species,site,plot,trt,treatment,pods,cover0,arsincover0,cover3,arsincover3,cover5,arsincover5
0,2010,CALE,Hyslop,4,6,Roundup 0.1,1.0,1.0,0.100167,2.00,0.141897,NaN,NaN
1,2010,CALE,Hyslop,12,7,Rdup/Bnvl 0.01,6.0,2.0,0.141897,1.00,0.100167,NaN,NaN
2,2010,CALE,Hyslop,13,5,Roundup 0.01,8.0,2.0,0.141897,2.00,0.141897,NaN,NaN
3,2010,CALE,Hyslop,15,1,Carrier Control,3.0,1.0,0.100167,1.00,0.100167,NaN,NaN
4,2010,CALE,Hyslop,17,3,Banvel 0.01,0.0,1.0,0.100167,2.00,0.141897,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2299,2011,RAOC,Botany,370,8,Rdup+Bnvl 0.2,NaN,0.2,0.044736,NaN,NaN,NaN,NaN
2300,2011,RAOC,Botany,377,3,Banvel 0.1,NaN,0.5,0.070770,0.30,0.054800,NaN,NaN
2301,2011,RAOC,Botany,379,4,Banvel 0.2,NaN,0.3,0.054800,0.20,0.044736,NaN,NaN
2302,2011,RAOC,Botany,380,2,No Spray,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2303,2011,RAOC,Botany,382,4,Banvel 0.2,NaN,0.2,0.044736,0.05,0.022363,NaN,NaN

In [163]:
final_data.to_csv("final_data_shawn.csv", index=False)

Then save the resulting data in a separate CSV file. [8 points]